//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookauthor
    {
        public System.Guid book_author_id { get; set; }
        public string book_id { get; set; }
        public Nullable<System.Guid> author_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual book book { get; set; }
    }
}
