//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.bookauthors = new HashSet<bookauthor>();
            this.wishlistitems = new HashSet<wishlistitem>();
        }
        
        [Key]
        [Display(Name ="ISBN")]
        public string book_id { get; set; }

        [Display(Name = "Name")]
        public string book_name { get; set; }

        [Display(Name = "Edition")]
        public decimal edition { get; set; }

        [Display(Name = "Year")]
        public short year_published { get; set; }

        //[EnumDataType(typeof(publisher))]
        [Display(Name = "Publisher")]
        public string publisher_name { get; set; }

        //[EnumDataType(typeof(genre))]
        [Display(Name = "Genre")]
        public string genre_name { get; set; }

        [ScaffoldColumn(false)]
        public string cover_photo_path { get; set; }

        [Display(Name = "Rating")]
        public Nullable<decimal> rating { get; set; }

        [Display(Name ="Summary")]
        public string summary { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual publisher publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookauthor> bookauthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlistitem> wishlistitems { get; set; }
    }
}
