<%@ Page Title="Authors" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Authors.aspx.cs" Inherits="LibraryApp.Admin.Authors" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h1><%: Title %></h1>
    <asp:Label ID="LabelAuthor" Text="" Visible="false" runat="server"></asp:Label>
    <p></p>
    <p></p>
    <asp:HyperLink NavigateUrl="~/Admin/AddAuthors" Text="Add New Author" runat="server" />
    <asp:GridView runat="server" ID="authorsGrid"
        ItemType="LibraryApp.Models.author" DataKeyNames="author_id" 
        SelectMethod="authorsGrid_GetData"
        UpdateMethod="authorsGrid_UpdateItem" DeleteMethod="authorsGrid_DeleteItem"
        AllowSorting="true" AllowPaging="true" PageSize="5"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false">
        <Columns>
            <%--<asp:DynamicField DataField="author_id" />--%>
            <%--<asp:DynamicField DataField="first_name" />
            <asp:DynamicField DataField="last_name" />--%>
            <asp:BoundField HeaderText="First Name" DataField="first_name" />
            <asp:BoundField HeaderText="Last Name" DataField="last_name" />
        </Columns>
        <EmptyDataTemplate>
            <asp:Label Text="No Authors" runat="server"></asp:Label>
        </EmptyDataTemplate>
     </asp:GridView>
</asp:Content>
