<%@ Page Title="Publishers" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Publishers.aspx.cs" Inherits="LibraryApp.Admin.Publishers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <h1><%: Title %></h1>
    <%--new publisher--%>
    <asp:HyperLink runat="server" NavigateUrl="~/Admin/AddPublisher" Text="Add New Publisher"></asp:HyperLink>
    <asp:GridView runat="server" id="publishersGrid" ItemType="LibraryApp.Models.publisher" DataKeyNames="publisher_name" SelectMethod="publishersGrid_GetData" UpdateMethod="publishersGrid_UpdateItem" DeleteMethod="publishersGrid_DeleteItem" AllowSorting="true" AllowPaging="true" PageSize="5" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="publisher_name" />
        </Columns>
    </asp:GridView>

</asp:Content>
